import "@/app/globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Luis Romero",
  description: "Generated by Next.js",
  icons: "/ICONO.ico", // Ruta correcta para el favicon
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
  style: ["normal", "italic"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/ICONO.ico" type="image/png" sizes="32x32" />
      </head>
      <body>{children}</body>
    </html>
  );
}
